# -*- coding: utf-8 -*-
"""Ejercicio Lógica Matemática

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kn9cpHQmSWWCm5Y_zFGzrTmHx1tsZsl
"""

dianac = int(input("Ingrese su día de nacimiento: "))
mesnac = int(input("Ingrese su mes de nacimiento: "))
añonac = int(input("Ingrese su año de nacimiento: "))
diaact = int(input("Ingrese el día actual: "))
mesact = int(input("Ingrese el mes actual: "))
añoact = int(input("Ingrese el año actual: "))

años = añoact - añonac
meses = mesact - mesnac
dias = diaact - dianac

if dias < 0 and mesact >= 1:
    dias += 30
    meses -= 1

if meses < 0 or dias < 0:
    meses += 12
    años -= 1

print("Su edad es:")
print(años, "años,", meses, "meses y", dias, "días")